---
kind: pipeline
name: checkers

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: checkers
  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
  commands:
    - ./autotest-checkers.sh
  secrets: [ github_token ]

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: litmus

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: litmus-v1
  image: ghcr.io/nextcloud/continuous-integration-litmus-php8.0:latest
  commands:
    - bash tests/travis/install.sh sqlite
    - bash apps/dav/tests/travis/litmus-v1/script.sh
- name: litmus-v2
  image: ghcr.io/nextcloud/continuous-integration-litmus-php8.0:latest
  commands:
    - bash tests/travis/install.sh sqlite
    - bash apps/dav/tests/travis/litmus-v2/script.sh

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: caldavtester-new-endpoint

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: caldavtester-new-endpoint
  image: ghcr.io/nextcloud/continuous-integration-litmus-php8.0:latest
  commands:
    - bash tests/travis/install.sh sqlite
    - bash apps/dav/tests/travis/caldav/install.sh
    - bash apps/dav/tests/travis/caldav/script-new-endpoint.sh

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: caldavtester-old-endpoint

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: caldavtester-old-endpoint
  image: ghcr.io/nextcloud/continuous-integration-litmus-php8.0:latest
  commands:
    - bash tests/travis/install.sh sqlite
    - bash apps/dav/tests/travis/caldav/install.sh
    - bash apps/dav/tests/travis/caldav/script-old-endpoint.sh

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: carddavtester-new-endpoint

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: carddavtester-new-endpoint
  image: ghcr.io/nextcloud/continuous-integration-litmus-php8.0:latest
  commands:
    - bash tests/travis/install.sh sqlite
    - bash apps/dav/tests/travis/carddav/install.sh
    - bash apps/dav/tests/travis/carddav/script-new-endpoint.sh

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: carddavtester-old-endpoint

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: carddavtester-old-endpoint
  image: ghcr.io/nextcloud/continuous-integration-litmus-php8.0:latest
  commands:
    - bash tests/travis/install.sh sqlite
    - bash apps/dav/tests/travis/carddav/install.sh
    - bash apps/dav/tests/travis/carddav/script-old-endpoint.sh

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: samba

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: sqlite-php8.0-samba-native
  image: ghcr.io/nextcloud/continuous-integration-samba-native-php8.0:latest
  commands:
    - smbd -D -FS &
    - ./autotest-external.sh sqlite smb-linux
    - wget https://codecov.io/bash -O codecov.sh
    - sh -c "if [ '$DRONE_BUILD_EVENT' = 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -P $DRONE_PULL_REQUEST -t 117641e2-a9e8-4b7b-984b-ae872d9b05f5 -f tests/autotest-external-clover-sqlite.xml; fi"
    - sh -c "if [ '$DRONE_BUILD_EVENT' != 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -t 117641e2-a9e8-4b7b-984b-ae872d9b05f5 -f tests/autotest-external-clover-sqlite.xml; fi"
    - sh -c "if [ '$DRONE_BUILD_EVENT' = 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -P $DRONE_PULL_REQUEST -t 117641e2-a9e8-4b7b-984b-ae872d9b05f5 -f tests/autotest-external-clover-sqlite-smb-linux.xml; fi"
    - sh -c "if [ '$DRONE_BUILD_EVENT' != 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -t 117641e2-a9e8-4b7b-984b-ae872d9b05f5 -f tests/autotest-external-clover-sqlite-smb-linux.xml; fi"
# Temporarily disabled because it times out for unknown reasons 98% of the time
#- name: sqlite-php8.0-samba-non-native
#  image: ghcr.io/nextcloud/continuous-integration-samba-non-native-php8.0:latest
#  commands:
#    - smbd -D -FS &
#    - ./autotest-external.sh sqlite smb-linux
#    - wget https://codecov.io/bash -O codecov.sh
#    - sh -c "if [ '$DRONE_BUILD_EVENT' = 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -P $DRONE_PULL_REQUEST -t 117641e2-a9e8-4b7b-984b-ae872d9b05f5 -f tests/autotest-external-clover-sqlite.xml; fi"
#    - sh -c "if [ '$DRONE_BUILD_EVENT' != 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -t 117641e2-a9e8-4b7b-984b-ae872d9b05f5 -f tests/autotest-external-clover-sqlite.xml; fi"
#    - sh -c "if [ '$DRONE_BUILD_EVENT' = 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -P $DRONE_PULL_REQUEST -t 117641e2-a9e8-4b7b-984b-ae872d9b05f5 -f tests/autotest-external-clover-sqlite-smb-linux.xml; fi"
#    - sh -c "if [ '$DRONE_BUILD_EVENT' != 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -t 117641e2-a9e8-4b7b-984b-ae872d9b05f5 -f tests/autotest-external-clover-sqlite-smb-linux.xml; fi"

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: sqlite-php8.0-webdav-apache

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: sqlite-php8.0-webdav-apache
  image: ghcr.io/nextcloud/continuous-integration-webdav-apache-php8.0:latest
  commands:
    - apache2ctl start
    - ./autotest-external.sh sqlite webdav-apachedrone
    - wget https://codecov.io/bash -O codecov.sh
    - sh -c "if [ '$DRONE_BUILD_EVENT' = 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -P $DRONE_PULL_REQUEST -t 117641e2-a9e8-4b7b-984b-ae872d9b05f5 -f tests/autotest-external-clover-sqlite.xml; fi"
    - sh -c "if [ '$DRONE_BUILD_EVENT' != 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -t 117641e2-a9e8-4b7b-984b-ae872d9b05f5 -f tests/autotest-external-clover-sqlite.xml; fi"
    - sh -c "if [ '$DRONE_BUILD_EVENT' = 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -P $DRONE_PULL_REQUEST -t 117641e2-a9e8-4b7b-984b-ae872d9b05f5 -f tests/autotest-external-clover-sqlite-webdav-apachedrone.xml; fi"
    - sh -c "if [ '$DRONE_BUILD_EVENT' != 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -t 117641e2-a9e8-4b7b-984b-ae872d9b05f5 -f tests/autotest-external-clover-sqlite-webdav-apachedrone.xml; fi"

services:
- name: cache
  image: ghcr.io/nextcloud/continuous-integration-redis:latest

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: nodb

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: nodb-php8.0
  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
  commands:
    - bash tests/drone-run-php-tests.sh || exit 0
    - NOCOVERAGE=true TEST_SELECTION=NODB ./autotest.sh sqlite

services:
- name: cache
  image: ghcr.io/nextcloud/continuous-integration-redis:latest

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: sqlite

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: sqlite-php8.0
  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
  commands:
    - bash tests/drone-run-php-tests.sh || exit 0
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite

services:
- name: cache
  image: ghcr.io/nextcloud/continuous-integration-redis:latest

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mariadb10.2-php8.0

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: mariadb10.2-php8.0
  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
  commands:
    - bash tests/drone-run-php-tests.sh || exit 0
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mariadb

services:
- name: cache
  image: ghcr.io/nextcloud/continuous-integration-redis:latest
- name: mariadb
  image: ghcr.io/nextcloud/continuous-integration-mariadb-10.2:10.2
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command:
    - --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mariadb10.4-php8.0

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: mariadb10.4-php8.0
  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
  commands:
    - bash tests/drone-run-php-tests.sh || exit 0
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mariadb

services:
- name: cache
  image: ghcr.io/nextcloud/continuous-integration-redis:latest
- name: mariadb
  image: ghcr.io/nextcloud/continuous-integration-mariadb-10.4:10.4
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command:
    - --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mariadb10.6-php8.0

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: mariadb10.6-php8.0
  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
  commands:
    - bash tests/drone-run-php-tests.sh || exit 0
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mariadb

services:
- name: cache
  image: ghcr.io/nextcloud/continuous-integration-redis:latest
- name: mariadb
  image: ghcr.io/nextcloud/continuous-integration-mariadb-10.6:latest
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command:
    - --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: postgres10-php8.0

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: postgres-php8.0
  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
  commands:
    - bash tests/drone-run-php-tests.sh || exit 0
    - sleep 10 # gives the database enough time to initialize
    - POSTGRES=10 NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh pgsql

services:
- name: cache
  image: ghcr.io/nextcloud/continuous-integration-redis:latest
- name: postgres-10
  image: ghcr.io/nextcloud/continuous-integration-postgres-10:postgres-10
  environment:
    POSTGRES_USER: oc_autotest
    POSTGRES_DB: oc_autotest
    POSTGRES_PASSWORD: owncloud
  tmpfs:
    - /var/lib/postgresql/data

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: postgres11-php8.0

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: postgres-php8.0
  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
  commands:
    - bash tests/drone-run-php-tests.sh || exit 0
    - sleep 10 # gives the database enough time to initialize
    - POSTGRES=11 NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh pgsql

services:
- name: cache
  image: ghcr.io/nextcloud/continuous-integration-redis:latest
- name: postgres-11
  image: ghcr.io/nextcloud/continuous-integration-postgres-11:postgres-11
  environment:
    POSTGRES_USER: oc_autotest
    POSTGRES_DB: oc_autotest
    POSTGRES_PASSWORD: owncloud
  tmpfs:
    - /var/lib/postgresql/data

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: postgres13-php8.0

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: postgres-php8.0
  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
  commands:
    - bash tests/drone-run-php-tests.sh || exit 0
    - sleep 10 # gives the database enough time to initialize
    - POSTGRES=13 NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh pgsql

services:
- name: cache
  image: ghcr.io/nextcloud/continuous-integration-redis:latest
- name: postgres-13
  image: ghcr.io/nextcloud/continuous-integration-postgres-13:postgres-13
  environment:
    POSTGRES_USER: oc_autotest
    POSTGRES_DB: oc_autotest
    POSTGRES_PASSWORD: owncloud
  tmpfs:
    - /var/lib/postgresql/data

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: postgres15-php8.0

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: postgres-php8.0
  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
  commands:
    - bash tests/drone-run-php-tests.sh || exit 0
    - sleep 10 # gives the database enough time to initialize
    - POSTGRES=15 NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh pgsql

services:
- name: cache
  image: ghcr.io/nextcloud/continuous-integration-redis:latest
- name: postgres-15
  image: ghcr.io/nextcloud/continuous-integration-postgres-15:latest
  environment:
    POSTGRES_USER: oc_autotest
    POSTGRES_DB: oc_autotest
    POSTGRES_PASSWORD: owncloud
  tmpfs:
    - /var/lib/postgresql/data

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: nodb-codecov

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: nodb-codecov
  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
  environment:
      CODECOV_TOKEN:
          from_secret: CODECOV_TOKEN
      XDEBUG_MODE: coverage
  commands:
    - phpenmod xdebug
    - TEST_SELECTION=NODB ./autotest.sh sqlite
    - wget https://codecov.io/bash -O codecov.sh
    - bash codecov.sh -Z -C $DRONE_COMMIT -f tests/autotest-clover-sqlite.xml

services:
- name: cache
  image: ghcr.io/nextcloud/continuous-integration-redis:latest

trigger:
  branch:
    - master
    - stable*
  event:
    - push

---
kind: pipeline
name: db-codecov

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: db-codecov
  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
  environment:
      CODECOV_TOKEN:
          from_secret: CODECOV_TOKEN
      XDEBUG_MODE: coverage
  commands:
    - phpenmod xdebug
    - TEST_SELECTION=QUICKDB ./autotest.sh sqlite
    - wget https://codecov.io/bash -O codecov.sh
    - bash codecov.sh -Z -C $DRONE_COMMIT -f tests/autotest-clover-sqlite.xml

services:
- name: cache
  image: ghcr.io/nextcloud/continuous-integration-redis:latest

trigger:
  branch:
    - master
    - stable*
  event:
    - push

---
kind: pipeline
name: object-store-s3

steps:
- name: minio
  image: ghcr.io/nextcloud/continuous-integration-minio:latest
  detach: true
  commands:
    - mkdir /s3data
    - minio server /s3data
  environment:
    MINIO_ROOT_USER: nextcloud
    MINIO_ROOT_PASSWORD: nextcloud
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: object-store
  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
  environment:
      OBJECT_STORE: s3
      CODECOV_TOKEN:
          from_secret: CODECOV_TOKEN
  commands:
    - phpenmod xdebug
    - ./tests/drone-wait-objectstore.sh
    - TEST_SELECTION=PRIMARY-s3 ./autotest.sh sqlite
    - wget https://codecov.io/bash -O codecov.sh
    - bash codecov.sh -C $DRONE_COMMIT -f tests/autotest-clover-sqlite.xml

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: object-store-azure

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: object-store
  image: ghcr.io/nextcloud/continuous-integration-php8.0:latest
  environment:
      OBJECT_STORE: azure
      CODECOV_TOKEN:
          from_secret: CODECOV_TOKEN
  commands:
    - phpenmod xdebug
    - ./tests/drone-wait-objectstore.sh
    - TEST_SELECTION=PRIMARY-azure ./autotest.sh sqlite
    - wget https://codecov.io/bash -O codecov.sh
    - bash codecov.sh -C $DRONE_COMMIT -f tests/autotest-clover-sqlite.xml

services:
- name: azurite
  image: ghcr.io/nextcloud/continuous-integration-azurite:latest
  environment:
    executable: blob

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: memcache-memcached

steps:
- name: submodules
  image: ghcr.io/nextcloud/continuous-integration-alpine-git:latest
  commands:
    - git submodule update --init
- name: memcache-memcached
  image: ghcr.io/nextcloud/continuous-integration-php8.0-memcached:latest
  commands:
    - phpenmod xdebug
    - service memcached restart
    - ./autotest.sh sqlite tests/lib/Memcache/MemcachedTest.php
    - wget https://codecov.io/bash -O codecov.sh
    - sh -c "if [ '$DRONE_BUILD_EVENT' = 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -P $DRONE_PULL_REQUEST -t 117641e2-a9e8-4b7b-984b-ae872d9b05f5 -f tests/autotest-clover-sqlite.xml; fi"
    - sh -c "if [ '$DRONE_BUILD_EVENT' != 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -t 117641e2-a9e8-4b7b-984b-ae872d9b05f5 -f tests/autotest-clover-sqlite.xml; fi"

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
---
kind: signature
hmac: 893f108e2269f7da269bf70b284e40d13932bd2697d0393686c42b287da5afcf
